<a href="https://colab.research.google.com/github/call-me-3v/Javascript_Async_Await/blob/master/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.random.rand(5)

array([0.93964802, 0.4686791 , 0.55093661, 0.67349653, 0.69170455])

In [4]:
np.random.randn(5)

array([-0.73264151,  0.22473141, -1.57718582,  0.46973353, -0.89425315])